### ISSUE TITLE
Add possibility to configure MinIO region instead of default usage 

### ISSUE THREAD

**Issue by ivan-sukhomlyn** [reportportal/commons-dao#579]
I tried to use Amazon S3 instead of self-hosted MinIO through passing S3 endpoint and IAM user access key ID and secret to the `RP_BINARYSTORE_MINIO_*` env variables.

And it works as expected but only in the default `us-east-1` region.

I have some errors after S3 bucket creating in another region:
```
io.minio.errors.ErrorResponseException: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2'
	at io.minio.MinioClient.executeReq(MinioClient.java:1203)
	at io.minio.MinioClient.execute(MinioClient.java:1065)
	at io.minio.MinioClient.updateRegionCache(MinioClient.java:1218)
	at io.minio.MinioClient.getRegion(MinioClient.java:1263)
	at io.minio.MinioClient.executeHead(MinioClient.java:1336)
	at io.minio.MinioClient.bucketExists(MinioClient.java:3370)
	at com.epam.ta.reportportal.filesystem.distributed.minio.MinioDataStore.save(MinioDataStore.java:59)
	at com.epam.ta.reportportal.binary.impl.CommonDataStoreService.save(CommonDataStoreService.java:44)
	at com.epam.ta.reportportal.binary.impl.UserBinaryDataServiceImpl.saveUserPhoto(UserBinaryDataServiceImpl.java:80)
	at com.epam.ta.reportportal.binary.impl.UserBinaryDataServiceImpl.saveUserPhoto(UserBinaryDataServiceImpl.java:63)
	at com.epam.ta.reportportal.core.events.handler.AttachDefaultPhotoEventHandler.attachPhoto(AttachDefaultPhotoEventHandler.java:64)
	at com.epam.ta.reportportal.core.events.handler.AttachDefaultPhotoEventHandler.lambda$handleContextRefresh$0(AttachDefaultPhotoEventHandler.java:57)
	at java.util.Optional.ifPresent(Optional.java:159)
```

It would be nice to have a chance to configure MinIO region for binary storage and don’t use only default `us-east-1` as defined for current MinIO client - https://github.com/reportportal/commons-dao/blob/32762b063577ace681a5392393e3a99a765c0a5b/src/main/java/com/epam/ta/reportportal/config/DataStoreConfiguration.java#L55
I assume that you can easily add the additional parameter as described in the doc for Java MinIO Client
http://minio.github.io/minio-java/io/minio/MinioClient.html#MinioClient-java.lang.String-java.lang.String-java.lang.String-java.lang.String-
Something like `datastore.minio.endpoint`configuration parameters that can be defined via `RP_BINARYSTORE_MINIO_REGION` environment variable during the starting of **service-authorization** and **service-api**

**Comment by ivan-sukhomlyn** [comment]
Added `datastore.minio.region` parameter for MinIO region definition during MinIO Java client initialisation.
Can be configured by `datastore.minio.region` property or `RP_BINARYSTORE_MINIO_REGION` env var  for **service-api** and **service-authorization**

Commits list with changes:
https://github.com/reportportal/commons-dao/commit/ba79f4e164ede30462983e546cc4348f8fc06e59
https://github.com/reportportal/service-api/commit/b15a6f421b4c80da0621e73779fa74770c6ded3a
https://github.com/reportportal/service-authorization/commit/3e312b167c605a76cd2621727c2f043d709c030b

**Comment by evjlobanova** [comment]
@ivan-sukhomlyn can we close issue?

**Comment by ivan-sukhomlyn** [comment]
Hi @evjlobanova 
Yes, it can be closed in case if the functionality will be realized in the coming version
